"""
Runtime helper for XAML Python IntelliSense type group access.

This module provides runtime support for the type group accessor pattern
(self.ComboBox.element_name, self.Button.element_name, etc.)

The stub files generated by the VS Code extension provide IDE autocomplete,
but this helper is needed to make the type groups work at runtime.

Usage:
    from pyrevit import forms
    from wpf_helpers import setup_element_groups

    class MyWindow(forms.WPFWindow):
        def __init__(self):
            forms.WPFWindow.__init__(self, 'MainWindow.xaml')
            setup_element_groups(self)

        def setup_ui(self):
            # Now both patterns work:
            self.project_combobox.SelectedIndex = 0  # Direct access
            self.ComboBox.project_combobox.ItemsSource = items  # Type group access
"""


class ElementGroup:
    """
    Runtime accessor for grouped XAML elements.

    Provides attribute access that delegates to the parent window,
    allowing patterns like self.ComboBox.my_combobox to work.
    """

    def __init__(self, window, element_names):
        """
        Initialize the element group.

        Args:
            window: The parent WPFWindow instance
            element_names: List of element names in this group
        """
        self._window = window
        self._names = element_names

    def __getattr__(self, name):
        """Delegate attribute access to the parent window."""
        if name.startswith('_'):
            return object.__getattribute__(self, name)
        if name in self._names:
            return getattr(self._window, name)
        raise AttributeError("'{}' has no element '{}'".format(type(self).__name__, name))

    def __iter__(self):
        """Iterate over all elements in this group."""
        for name in self._names:
            yield getattr(self._window, name)

    def __len__(self):
        """Return the number of elements in this group."""
        return len(self._names)

    @property
    def names(self):
        """Return the list of element names in this group."""
        return list(self._names)


def setup_element_groups(window):
    """
    Set up type group accessors on a WPFWindow instance.

    This function inspects all attributes of the window, identifies
    WPF control types, and creates group accessors for each type.

    Call this after the XAML has been loaded (in __init__ after
    calling the parent constructor).

    Args:
        window: A WPFWindow instance with XAML already loaded

    Example:
        class MyWindow(forms.WPFWindow):
            def __init__(self):
                forms.WPFWindow.__init__(self, 'MainWindow.xaml')
                setup_element_groups(self)
    """
    # Build a set of type names for matching (more reliable than isinstance in IronPython)
    type_names = {
        'Button', 'TextBox', 'ComboBox', 'CheckBox', 'RadioButton',
        'ListView', 'ListBox', 'DataGrid', 'TextBlock', 'Label',
        'ProgressBar', 'Slider', 'TabControl', 'TabItem', 'Image',
        'Menu', 'MenuItem', 'TreeView', 'TreeViewItem', 'ToolBar',
        'StatusBar', 'Expander', 'GroupBox', 'ScrollViewer',
        'PasswordBox', 'RichTextBox', 'DatePicker', 'Calendar',
        'Grid', 'StackPanel', 'WrapPanel', 'DockPanel', 'Canvas', 'Border',
    }

    # Initialize groups dictionary
    groups = {name: [] for name in type_names}

    # Find all named elements and group by type
    for attr_name in dir(window):
        if attr_name.startswith('_'):
            continue

        try:
            element = getattr(window, attr_name)
            # Use type name matching instead of isinstance (more reliable in IronPython)
            type_name = type(element).__name__
            if type_name in type_names:
                groups[type_name].append(attr_name)
        except (AttributeError, TypeError):
            # Skip attributes that can't be accessed
            pass

    # Create group accessors for non-empty groups
    for group_name, element_names in groups.items():
        if element_names:
            group = ElementGroup(window, element_names)
            setattr(window, group_name, group)


def get_elements_by_type(window, wpf_type):
    """
    Get all elements of a specific WPF type from a window.

    Args:
        window: A WPFWindow instance
        wpf_type: The WPF type to filter by (e.g., ComboBox)

    Returns:
        List of (name, element) tuples for all matching elements
    """
    elements = []

    for attr_name in dir(window):
        if attr_name.startswith('_'):
            continue

        try:
            element = getattr(window, attr_name)
            if isinstance(element, wpf_type):
                elements.append((attr_name, element))
        except (AttributeError, TypeError):
            pass

    return elements
